#!/bin/sh

set -eu

if [ "${1:-}" = "" ]
then
	echo "${0}: Please specify a project to upgrade" >&2
	exit 1
fi

PROJECT="${1}"

Git () {
	URL="${1}"
	TARGET="${2}"
	SUBDIR="${3:-}"

	rm -rf ${TARGET}
	mkdir -p ${TARGET}
	git clone "${URL}" ${TARGET}/.clone
	git --git-dir=${TARGET}/.clone/.git log --stat > ${TARGET}/git.log
	mv ${TARGET}/.clone/${SUBDIR}/* ${TARGET}
	rm -rf ${TARGET}/.clone
}

case "${PROJECT}" in
	bootstrap)
		Git git://github.com/twbs/bootstrap.git ${PROJECT} dist/
		;;

	jquery)
		mkdir -p ${PROJECT}
		wget -Ojquery/jquery.js http://code.jquery.com/jquery.js
		;;

	*)
		echo "${0}: Unknown project '${PROJECT}'" >&2
		exit 1
		;;
esac

if [ -x "_hooks/${PROJECT}" ]
then
	echo "I: Running hook ${PROJECT}..."
	cd ${PROJECT}
	../_hooks/${HOOK}
fi
