# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import django_enumfield.db.fields
import hba1c.session.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(default=django.utils.crypto.get_random_string, max_length=12, unique=True)),
                ('stage', django_enumfield.db.fields.EnumField(default=10, enum=hba1c.session.enums.StageEnum)),
                ('generating_pdf', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='session.Session'),
        ),
    ]
