# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='session',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
